# 参考 http://www.tuicool.com/articles/veUjQba
# Web容器配置
server:
  port: 8761
  undertow:
    accesslog:
      # 开启Undertow访问日志
      enabled: true
      dir: /data/ghylogs/

eureka:
#  #EurekaInstanceConfigBean
#  instance:
#    preferIpAddress: true
#    instanceId: ${spring.cloud.client.hostname}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
#    healthcheck:
#      enabled: false
    #默认情况下本服务将要注册到的Eureka服务器
    serviceUrl:
      defaultZone: http://192.168.51.184:8761/eureka/

# Log 配置 级别大写 TRACE|DEBUG|INFO|WARN|ERROR
logging:
  level:
    #root: INFO
    com.xiaowo: DEBUG
spring:
  velocity:
      suffix: .html
      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      date-tool-attribute: dateTool
      number-tool-attribute: numberTool
      toolbox-config-location: toolbox.xml
      expose-spring-macro-helpers: true
      expose-request-attributes: true
      expose-session-attributes: true
  rabbitmq:
    host: 192.168.51.184
    port: 5672
    virtualHost: /
    username: guhaiyan
    password: guhaiyan
